#!/bin/sh

set -ex

INPUT=${1}
FPS=29.970
# QUALITY: less is better
QUALITY=26

if [ -z "${INPUT}" ]; then
	echo usage: ${0} inputfile
	exit 1
fi

OUTPUT="${INPUT}.mkv"

rm -f "${OUTPUT}" x.{mp4,264,y4m,wav}
#mplayer -vo yuv4mpeg:file=x.y4m -ao pcm:fast:file=x.wav -fps ${FPS} -noframedrop "${INPUT}"
#-aspect 16:9
mkfifo x.y4m
#ffmpeg -i "${INPUT}" -f yuv4mpegpipe - > x.y4m &
mplayer "mf://frame-*.png" -noframedrop -fps ${FPS} -vo yuv4mpeg:file=x.y4m
~/tmp/x264/x264 -q ${QUALITY} --progress -o x.264 x.y4m
#ffmpeg -i "${INPUT}" -s qvga -f yuv4mpegpipe - > x.y4m &
#~/tmp/x264/x264 -q ${QUALITY} --progress --pass 3 -o x.264 x.y4m
rm x.y4m
mkfifo x.wav
ffmpeg -i "${INPUT}" -f wav - > x.wav &
faac -q 10 x.wav -o x.aac
rm x.wav
MP4Box -fps ${FPS} -add x.264 -add x.aac x.mp4
rm x.{aac,264}
mkvmerge -o "${OUTPUT}" x.mp4
[ -f "$OUTPUT" ] || exit 1
rm x.mp4
ls -l "${INPUT}" "${OUTPUT}"
echo Done
