name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
        - os: windows-latest
        - os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt install --yes g++-multilib
        fi
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v2
      with:
        name: artifact-${{matrix.os}}
        path: |
          ${{github.workspace}}/build/ray
          ${{github.workspace}}/build/ray.map
          ${{github.workspace}}/build/ray-single
          ${{github.workspace}}/build/ray-single.map
          ${{github.workspace}}/build/MinSizeRel/ray.exe
          ${{github.workspace}}/build/MinSizeRel/ray.map
          ${{github.workspace}}/build/MinSizeRel/ray-single.exe
          ${{github.workspace}}/build/MinSizeRel/ray-single.map
