name: Measure

on:
  push:
    branches: [ master ]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

env:
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        sudo apt update
        sudo apt install --yes g++-multilib
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install --yes valgrind:i386
        ../benchmark.sh > output.txt

    # gh-pages branch is updated and pushed automatically with extracted benchmark data
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Benchmark
        tool: 'customSmallerIsBetter'
        output-file-path: ${{github.workspace}}/build/output.txt
        # Access token to deploy GitHub Pages branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Push and deploy GitHub pages branch automatically
        auto-push: true
